build:
  maxIssues: 0
config:
  validation: true
style:
  active: true
  MagicNumber:
    active: false
  UnusedPrivateMember:
    active: true
complexity:
  active: true
  LongMethod:
    threshold: 60
  TooManyFunctions:
    thresholdInFiles: 11
naming:
  active: true
